come back to original version

diff --git a/.github/workflows/label-blocked-issues.yml b/.github/workflows/label-blocked-issues.yml
--- a/.github/workflows/label-blocked-issues.yml
+++ b/.github/workflows/label-blocked-issues.yml
@@ -33,8 +33,8 @@ jobs:
               -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/$issue")
-            http_status=$(echo "$status" | tail -n1)
-            body=$(echo "$status" | head -n-1)
+            http_status=$(tail -n1 <<< "$status")
+            body=$(head -n-1 <<< "$status")
 
             if [[ "$http_status" != "200" ]]; then
               echo "HTTP Status: $http_status, Error fetching status for issue #$issue"
@@ -66,35 +66,36 @@ jobs:
       - name: Label or Unlabeled Issue as Blocked
         if: ${{ env.blocked == 'true' }}
         run: |
-          echo "Labeling or Unlabeling issue as blocked..."
+          echo "Labeling issue as blocked..."
           echo "GitHub Repository: ${{ github.repository }}"
           echo "Issue Number: ${{ github.event.issue.number }}"
 
-          if [[ "$found_blocked" == true ]]; then
-            # Label the issue as blocked
-            response=$(curl -s -w "%{http_code}" -X POST \
-              -H "Accept: application/vnd.github.v3+json" \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              -d '{"labels": ["blocked"]}' \
-              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels")
-            http_status=$(echo "$response" | tail -n1)
+          response=$(curl -s -w "%{http_code}" -X POST \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -d '{"labels": ["blocked"]}' \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels")
+          http_status=$(tail -n1 <<< "$response")
 
-            if ! [[ "$http_status" =~ ^2 ]]; then
-              echo "Failed to add 'blocked' label: HTTP $http_status"
-              exit 1
-            fi
-          else
-            # Unlabel the issue as blocked
-            response=$(curl -s -w "%{http_code}" -X DELETE \
-              -H "Accept: application/vnd.github.v3+json" \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/blocked")
-            http_status=$(echo "$response" | tail -n1)
+          if ! [[ "$http_status" =~ ^2 ]]; then
+            echo "Failed to add 'blocked' label: HTTP $http_status"
+            exit 1
+          fi
 
-            if [[ "$http_status" == "404" ]]; then
-              echo "'Blocked' label was not present on the issue."
-            elif ! [[ "$http_status" =~ ^2 ]]; then
-              echo "Failed to remove 'blocked' label: HTTP $http_status"
-              exit 1
-            fi
+      - name: Unlabeled Issue if No Blocked Dependencies
+        if: ${{ env.blocked == 'false' }}
+        run: |
+          echo "Removing 'blocked' label from the issue..."
+          echo "GitHub Repository: ${{ github.repository }}"
+          echo "Issue Number: ${{ github.event.issue.number }}"
+          response=$(curl -s -w "%{http_code}" -X DELETE \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/blocked")
+          http_status=$(tail -n1 <<< "$response")
+          if [[ "$http_status" == "404" ]]; then
+            echo "'Blocked' label was not present on the issue."
+          elif ! [[ "$http_status" =~ ^2 ]]; then
+            echo "Failed to remove 'blocked' label: HTTP $http_status"
+            exit 1
           fi
