combine two last steps into one

diff --git a/.github/workflows/label-blocked-issues.yml b/.github/workflows/label-blocked-issues.yml
--- a/.github/workflows/label-blocked-issues.yml
+++ b/.github/workflows/label-blocked-issues.yml
@@ -64,38 +64,36 @@ jobs:
           fi
 
       - name: Label or Unlabeled Issue as Blocked
-        if: ${{ env.blocked == 'true' && github.event_name != 'closed' }}
         run: |
-          echo "Labeling issue as blocked..."
+          echo "Processing issue..."
           echo "GitHub Repository: ${{ github.repository }}"
           echo "Issue Number: ${{ github.event.issue.number }}"
-
-          response=$(curl -s -w "%{http_code}" -X POST \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d '{"labels": ["blocked"]}' \
-            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels")
-          http_status=$(tail -n1 <<< "$response")
-
-          if ! [[ "$http_status" =~ ^2 ]]; then
-            echo "Failed to add 'blocked' label: HTTP $http_status"
-            exit 1
-          fi
-
-      - name: Unlabeled Issue if No Blocked Dependencies
-        if: ${{ env.blocked == 'false' && github.event_name != 'closed' }}
-        run: |
-          echo "Removing 'blocked' label from the issue..."
-          echo "GitHub Repository: ${{ github.repository }}"
-          echo "Issue Number: ${{ github.event.issue.number }}"
-          response=$(curl -s -w "%{http_code}" -X DELETE \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/blocked")
-          http_status=$(tail -n1 <<< "$response")
-          if [[ "$http_status" == "404" ]]; then
-            echo "'Blocked' label was not present on the issue."
-          elif ! [[ "$http_status" =~ ^2 ]]; then
-            echo "Failed to remove 'blocked' label: HTTP $http_status"
-            exit 1
+          
+          if [[ "${{ env.blocked }}" == 'true' ]]; then
+            echo "Labeling issue as blocked..."
+            response=$(curl -s -w "%{http_code}" -X POST \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -d '{"labels": ["blocked"]}' \
+              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels")
+            http_status=$(tail -n1 <<< "$response")
+          
+            if ! [[ "$http_status" =~ ^2 ]]; then
+              echo "Failed to add 'blocked' label: HTTP $http_status"
+              exit 1
+            fi
+          else
+            echo "Removing 'blocked' label from the issue..."
+            response=$(curl -s -w "%{http_code}" -X DELETE \
+              -H "Accept: application/vnd.github.v3+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/blocked")
+            http_status=$(tail -n1 <<< "$response")
+          
+            if [[ "$http_status" == "404" ]]; then
+              echo "'Blocked' label was not present on the issue."
+            elif ! [[ "$http_status" =~ ^2 ]]; then
+              echo "Failed to remove 'blocked' label: HTTP $http_status"
+              exit 1
+            fi
           fi
