adjust step naming

diff --git a/.github/workflows/label-blocked-issues.yml b/.github/workflows/label-blocked-issues.yml
--- a/.github/workflows/label-blocked-issues.yml
+++ b/.github/workflows/label-blocked-issues.yml
@@ -67,7 +67,7 @@ jobs:
             echo "blocked=false" >> $GITHUB_ENV
           fi
 
-      - name: Label or Unlabeled Issue as Blocked
+      - name: Label Issue as Blocked
         if: ${{ env.blocked == 'true' }}
         run: |
           echo "Labeling issue as blocked..."
@@ -89,28 +89,17 @@ jobs:
       - name: Unlabeled Issue if No Blocked Dependencies
         if: ${{ env.blocked == 'false' }}
         run: |
-          echo "Removing 'blocked' label from dependent issues..."
+          echo "Removing 'blocked' label from the issue..."
           echo "GitHub Repository: ${{ github.repository }}"
           echo "Issue Number: ${{ github.event.issue.number }}"
-
-          # Extract dependent issue numbers from the issue body
-          dependent_issues=$(jq -r '.issue.body' $GITHUB_EVENT_PATH | grep -oP "(?<=^|\s)#\d+(?=\s|$)" | sed 's/#//g' || true)
-
-          for dependent_issue in $dependent_issues; do
-            # Remove 'blocked' label from dependent issue
-            echo "Removing 'blocked' label from dependent issue #$dependent_issue..."
-            response=$(curl -s -w "%{http_code}" -X DELETE \
-              -H "Accept: application/vnd.github.v3+json" \
-              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              "https://api.github.com/repos/${{ github.repository }}/issues/$dependent_issue/labels/blocked")
-            http_status=$(tail -n1 <<< "$response")
-
-            if [[ "$http_status" == "404" ]]; then
-              echo "'Blocked' label was not present on dependent issue #$dependent_issue."
-            elif ! [[ "$http_status" =~ ^2 ]]; then
-              echo "Failed to remove 'blocked' label from dependent issue #$dependent_issue: HTTP $http_status"
-              exit 1
-            fi
-          done
-      
-      
+          response=$(curl -s -w "%{http_code}" -X DELETE \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/blocked")
+          http_status=$(tail -n1 <<< "$response")
+          if [[ "$http_status" == "404" ]]; then
+            echo "'Blocked' label was not present on the issue."
+          elif ! [[ "$http_status" =~ ^2 ]]; then
+            echo "Failed to remove 'blocked' label: HTTP $http_status"
+            exit 1
+          fi
